site_name: Mes Recettes de Cuisine
theme:
  name: material
  language: fr  # Pour avoir l'interface en français
  palette:
    primary: deep orange # Couleur thématique "cuisine"
    accent: orange

nav:
  - Accueil: index.md
  - Plats: 
      - Poulet au curry: plats/poulet-curry.md
  - Desserts:
      - Fondant au chocolat: desserts/fondant.md